version: '3'

services:
   wordpress007:
     depends_on:
       - db007
     image: wordpress:latest
     volumes:
       - ./wp_data007:/var/www/html
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db007:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: my_wordpress_db_password

   db007:
     image: mariadb
     volumes:
       - ./db_data007:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password
volumes:
    wp_data007:
        external: true
    db_data007:
        external: true
